# Generated by Django 6.0.2 on 2026-03-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
