# Generated by Django 5.2.8 on 2026-03-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_campusreport_reportevidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='scanned_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
